#:import MainScreen mobileApp.screens.main_screen.MainScreen
#:import DashboardScreen mobileApp.screens.dashboard_screen.DashboardScreen
#:import ExpensesScreen mobileApp.screens.expenses_screen.ExpensesScreen
#:import DocumentsScreen mobileApp.screens.documents_screen.DocumentsScreen
#:import AddVehicleScreen mobileApp.screens.add_vehicle_screen.AddVehicleScreen


<MainManager>:
    MainScreen:
    DashboardScreen:
    ExpensesScreen:
    DocumentsScreen:
    AddVehicleScreen:
